export const products = [
  {
    id: 1,
    name: 'Bailey',
    mainImage: '1nYvIfS8k6qB1hyIDT6GhaDprQLO17cc9',
    images: [
      '1nYvIfS8k6qB1hyIDT6GhaDprQLO17cc9',
      '1idVLrEK91YFmzZ5ZtyKARM0jmGUUk0Mr',
      '12Kz2MLpQp9MEYo2IKzRZkF9G_8SNA-ku',
      '1-cj-u7AM6J15GLvTZ86aOUrv275gHJVs',
    ],
    description: 'A banded strapless Mikado dress style with plunging detail at center front. Features a center slit, back-channel mesh detailing and removable large bow.',
    collection: 'springSummer25',
  },
  {
    id: 2,
    name: 'Billie',
    mainImage: '1XNk8uLe2o5bvGzbCqdt1QNrM7arx-gg9',
    images: [
      '1XNk8uLe2o5bvGzbCqdt1QNrM7arx-gg9',
      '1l0Op63YQ7MIPySV2neHuENvzgoo055Jw',
      '11tCUVl-_6SN-SzbQjNQGEiS1jl7yd3et',
      '1Pz_KTn-Y09Yny-Nyz94kV2ObKwGo49ix',
    ],
    description: 'Satin Jasmine floral appliqué on Chantilly lace with sparkle. Figure flattering A-line silhouette with detachable Satin faced organza and a cascading peplum train.',
    collection: 'springSummer25',
  },
  {
    id: 3,
    name: 'Blake',
    mainImage: '1qTpwyvX6JEpEZC_fGrO3tF4Gwn2SdUnJ',
    images: [
      // '122GyVXGSb5YTk_hjT53q6J91zZL-4Gsv',
      // '1VJ2GpVI_SATLSKAWzWjUg1yehM_Tjh37',
      '1qTpwyvX6JEpEZC_fGrO3tF4Gwn2SdUnJ',
      '1FElAwPXL_K0vBFApnvuwc_qXSpj5wvFD',
    ],
    description: 'A strapless Mikado mermaid style. Three-dimensional floral appliqués at bust line and train, with sheer corset back and contrasting boning channels.',
    collection: 'springSummer25',
  },
  {
    id: 4,
    name: 'Blossom',
    mainImage: '15HSj3bKQi7uN3r9b47gq5J9o5P-3GQxL',
    images: [
      '15HSj3bKQi7uN3r9b47gq5J9o5P-3GQxL',
      '1CAzylV4Wtq_s--dTpRFnypTOLV8dS0wh',
      '1OrznOZY0qcdHtTouKeTURZ_0iF9nQ023',
    ],
    description: 'This convertible strapless A-line silhouette is beaded with a cherry blossom floral lace. Features a removable halter top, taffeta train and fitted removable sleeves. Three looks in one.',
    collection: 'springSummer25',
  },
  {
    id: 5,
    name: 'Brielle',
    mainImage: '1mAjlmeQyCdlglNlmha-T_-s5JkmpYPy6',
    images: [
      '1mAjlmeQyCdlglNlmha-T_-s5JkmpYPy6',
      '1alPnn2H0SAZhJRlPd9rI7fAAWlYrfUWN',
      '1ajCEYXrACbHIPxa5_kMk8P62g9EGbxJf',
    ],
    description: 'Satin D\'Hauteur pleated high-waist ball gown features a high side slit and pocket. Long sleeve styling with stand collar, lace top and pronounced satin 3-dimensional floral appliqué.',
    collection: 'springSummer25',
  },
  {
    id: 6,
    name: 'Bellarose',
    mainImage: '1GTtnNeX34t_iGi7wRX5yT0fC8yxWKMp9',
    images: [
      '1GTtnNeX34t_iGi7wRX5yT0fC8yxWKMp9',
      '1RqN57kPQqdEIN67hpQIdppkk4iSa--LA',
      '1CUNC3z2r-rIxWmiFa6Aj3QkPWgYysn1p',
      '1KoAmY2PVAF3n3J_I83F5PDXU1tzNeZ7F',
    ],
    description: 'White organdy layered with contrasting color, plunging sweetheart neckline with crystal appliqué sarong-styled short dress with removable ceremonial over-skirt and removable circular pleated sleeve. Color offerings: white, pale lavender, pale blue, pale pink and red. Additional colors available upon request.',
    collection: 'springSummer25',
  },
  {
    id: 7,
    name: 'Belgique',
    mainImage: '1Barlvm_0RhcSk5DxGLhRzwcBz4hIiBrh',
    images: [
      '1Barlvm_0RhcSk5DxGLhRzwcBz4hIiBrh',
      '13bCKGCrDNLrqbtxzNMgLklRA-uQbEfX1',
      '1UlUYRaH5wr03GlErHUZlRrkjdm0RnHFF',
    ],
    description: 'A mermaid style that features a corset-boning bodice. Embroidered, sheer styling with beaded crystal droplets, ostrich-feather bottom, and removable fitted sleeve',
    collection: 'springSummer25',
  },


  {
    id: 8,
    name: 'Bowie',
    mainImage: '1I3XKi1G7gdpn1Q1Kp7nQGk6M1KEfvgPu',
    images: [
      '1I3XKi1G7gdpn1Q1Kp7nQGk6M1KEfvgPu',
      '1JxUm-L17rqF2MwJXyg3ZWf7PPvFu0U3-',
    ],
    description: 'A three-dimensional cascade floral lace appliqué Satin organza ball gown, with Col Bateau neckline and detachable floral neck band.',
    collection: 'springSummer25',
  },
  {
    id: 9,
    name: 'Bradie',
    mainImage: '1BdlO6driG2y235tIbxIhPiEbxvqoAYlI',
    images: [
      '1BdlO6driG2y235tIbxIhPiEbxvqoAYlI',
      '1y95MSoJHZuD8viD0OpWyC3vFsHXTrzF2',
      '1DcrbP7UrIUw2shhzPuvmKYDCm0aJgK15',
    ],
    description: 'A diagonal sequined pattern designed to complement the woman\'s body. Mermaid styling with a plunging v-neckline.',
    collection: 'springSummer25',
  },
  {
    id: 10,
    name: 'Brenna',
    mainImage: '1mVRcoqRA2TkJ1r_PyqddO2w10tQi4Ge0',
    images: [
      '1mVRcoqRA2TkJ1r_PyqddO2w10tQi4Ge0',
      '1XFAY1GUFkJlwN_SBxVN1_4sKObYcsb34',
      '1VoOBJZOoURQQbhIjH8E6vdHP2A3MDxOO',
    ],
    description: 'Corded floral lace on a boat neckline style dress. Features a one shoulder flower detail and a detachable cape',
    collection: 'springSummer25',
  },

  {
    id: 11,
    name: 'Brinkley',
    mainImage: '1Po2osELpTyxMwakqMcAAWFZ8BJ1dGV2Z',
    images: [
      '1Po2osELpTyxMwakqMcAAWFZ8BJ1dGV2Z',
      '1xA43mrUV6bznrmHrBxw2P8_qjc3BSpCY',
    ],
    description: 'A three-dimensional satin floral sweetheart neckline with shimmering bodice and Mikado side slit skirt. Features a one shoulder removable drape with bow detailing.',
    collection: 'springSummer25',
  },
  {
    id: 12,
    name: 'Bronte',
    mainImage: '1r7QsjfpO5lHEYAyk70CnctKUw3HGVPMR',
    images: [
      '1r7QsjfpO5lHEYAyk70CnctKUw3HGVPMR',
      '1rOYspJO2L-umF_XZf2hgoafjHaEnljwY',
    ],
    description: 'Satin D\'Hauteur A-line strapless dress with back train and three-dimensional shimmering organza floral and leaves appliqué. Available with a removable multi layered circular sleeve and neck band.',
    collection: 'springSummer25',
  },
  {
    id: 13,
    name: 'Brooklyn',
    mainImage: '1G4hz852bwcPNboFdZX40gwTaK0bxkh1h',
    images: [
      '1G4hz852bwcPNboFdZX40gwTaK0bxkh1h',
      '1b1FlFMIXxzKCqkr7LPsEJ-d8dxlvOWLH',
      '13D-7ku5p6rmuCZ1L7MxsNsDZ1YQPB1t7',
    ],
    description: 'A Mikado halter-top style with figure-flattering mermaid shape. Features crossed crystal channels at neckline and a cathedral length train.',
    collection: 'springSummer25',
  },
  {
    id: 14,
    name: 'Adele',
    mainImage: '1xuv0W_YaSs5MzOkuCV9DQqoE9XqYE1-H',
    images: [
      '1xuv0W_YaSs5MzOkuCV9DQqoE9XqYE1-H',
      '1_rfvwoisPBmmiN1VJhTgfgOoGhrZzh4P',
      '19FciFAKt0-lR2CsvjHMPXMIVbhLLuQ_4',
    ],
    description: 'A convertible style with a full silk chiffon detachable skirt adorned with ostrich feathers. Ruffled neckline and exposed boning at the waistline.',
    collection: 'springSummer24',
  },
  {
    id: 15,
    name: 'Anna',
    mainImage: '1AivRpLY4PKrHlLAACEdJUEW0ekJ_vmQD',
    images: [
      '1AivRpLY4PKrHlLAACEdJUEW0ekJ_vmQD',
      '1b2fzBylwBB9rg-ooPqKjm_rkkUNDYrW5',
      '1ww0ukXx9z5OII44OekR5BgWDcwyy_jSZ',
    ],
    description: 'A classic Aline Satin D\'Hauteur dress with tulle halter top, embrodery, pearl lace details and Swarovski crystal stones. Sheer organdy cape is fully removable.',
    collection: 'springSummer24',
  },
  {
    id: 16,
    name: 'Antoinette',
    mainImage: '1y66yCuW6LdVskUaN1rFnPZFKg9aVXg-n',
    images: [
      '1y66yCuW6LdVskUaN1rFnPZFKg9aVXg-n',
      '1TLyXRsMBsqCavFJWVIV_1YnarTWsF14H',
    ],
    description: 'A classic white Satin fit and flare gown with princess seamed styling. Flattering ceremonial dress with peaked bra cup detail and optional rhinestone pendant centered at the bustline.',
    collection: 'springSummer24',
  }
];